apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-gold-xfs
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB: "10"
  sizeRange: "[20-12000]Gi"
  fsType: "xfs"
  reclaimPolicy: "Delete"
  classVersion: "2"