apiVersion: v1
kind: Pod
metadata:
    name: testclient
    namespace: default
spec:
    containers:
    - name: kafka
      image: confluentinc/cp-kafka:4.0.1-1
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"