isClusterService: false
serviceType: "NodePort"
middleware:
  kubernetes:
    enabled: false
  errors:
    enabled: true
  log:
    enabled: true
  etcd:
    enabled: true
    zones:
    - "example.com."
    endpoint: "http://etcd-cluster.default:2379"
