isClusterService: false
serviceType: "LoadBalancer"
serviceProtocol: "TCP"
middleware:
  kubernetes:
    enabled: false
  etcd:
    enabled: true
    zones:
    - "example.com."
    endpoint: "http://etcd-cluster-client.default:2379"